name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read 

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # STAP 1: Je moet de code eerst ophalen (Checkout), anders kan Sonar niks scannen!
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Belangrijk voor een goede analyse van de historie

      # STAP 2: De daadwerkelijke scan
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3.1.0 # Gebruik de nieuwste versie
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=UsherM8_yourairtravel
            -Dsonar.organization=usherm8
            -Dsonar.sources=.
            -Dsonar.php.exclusions=vendor/**,tests/**
          projectBaseDir: .
